# Generated by Django 2.2.24 on 2022-05-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20220529_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='text',
            field=models.TextField(verbose_name='Текст жалобы'),
        ),
    ]
