# Generated by Django 2.2.24 on 2022-05-29 01:53

from django.db import migrations

import phonenumbers

def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if not flat.owners_phonenumber:
            continue

        parsed_phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        normalized_phone = phonenumbers.format_number(parsed_phone, phonenumbers.PhoneNumberFormat.E164)
        flat.owner_pure_phone = normalized_phone
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers)
    ]
