# Generated by Django 2.2.24 on 2022-06-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20220529_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(blank=True, to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
