# Generated by Django 2.2.24 on 2022-06-06 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20220601_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='owner_phonenumber',
        ),
    ]
