# Generated by Django 2.2.24 on 2022-06-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_remove_owner_owner_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='flat_owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(related_name='flat_owners', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
